version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry_db
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build: ./server
    container_name: backend
    environment:
      DB_HOST: timescaledb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: telemetry_db
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      - backend

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  timescale-data:
